


CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FACE_SIZE = (200, 200)
KNOWN_FACE_DIR = "data/known_faces"
MODEL_PATH = "models/face_model.yml"
LABELS_PATH = "models/labels.json"



YOLO_MODEL_DIR = 'models/best.pt'

YOLO_CONFIDENCE_THRESHOLD = 0.50

MIN_PERSON_HEIGHT_RATIO = 0.35

MIN_CENTER_X_RATIO = 0.3
MAX_CENTER_X_RATIO = 0.7



KNOW_FACES_DIR = 'data/known_faces'
ENROLLMENT_IMAGE_COUNT = 30
ENROLL_IMAGE_CAPTURE_DELAY= 0.3


FACE_EMBEDDINGS_DIR = 'data/face_embeddings'
FACE_EMBEDDINGS_FILE = 'data/face_embeddings/known_faces.pkl'
FACE_RECOGNITION_THRESHOLD = 0.55







